name: ""
relative_permalinks: true
markdown: kramdown
highlighter: true
# paginate: 12
# paginate_path: "blog/page:num"

author :
  name : David Kim
  email : productloverssf@gmail.com
  github : productmanagers
  twitter : PMFastTrack
  feedburner : PMFastTrackBlog

production_url : http://productmanagementfasttrack.com
BASE_PATH : false
ASSET_PATH: false

# Google analytics
analytics:
  provider: google
  google:
    tracking_id: 'UA-43170427-1'
  getclicky:
    site_id:

comments:
  provider : disqus
  disqus:
    short_name: techproductmanager
